workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      groups:
        - $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FIREBASE_PROJECT: "sse3401-lab6-9f8ac"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK with Flutter
        script: |
          flutter build apk --debug
      - name: Create debug and test APK
        script: |
          set -ex
          cd android
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug -Ptarget="D:\lab_5_2\lib\main.dart"
      - name: Run Firebase Test Lab Tests
        script: |
          set -ex
          echo $GCLOUD_KEY_FILE | base64 --decode > ./gcloud_key_file.json
          gcloud auth activate-service-account --key-file=gcloud_key_file.json
          gcloud --quite config set project $FIREBASE_PROJECT
          
          gcloud firebase test android run \
          --type instrumentation \
          --app build/app/outputs/apk/debug/apk-debug.apk \
          --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
          --timeout 3m

    artifacts:
        - build/**/outputs/**/*.apk
        - build/**/outputs/**/*.aab
        - build/**/outputs/**/mapping.txt
        - flutter_drive.log